name: HellcraftManager
version: 2.0-SNAPSHOT
main: sebastnun.hellcraft.Main
api-version: 1.17
author: Sebastnun
description: El controlador del servidor Hellcraft
load: POSTWORLD
depend: []

permissions:
  hellcraft.admin:
    description: Dado a los admins de hellcraft
  hellcraft.hell:
    description: Otorga el poder de usar la HellBench
  hellcraft.help:
    description: Helper de Hellcraft


commands:
  helltime:
    description: Obtener el tiempo total de baneo
    usage: /<command>
  afk:
    description: Ponerte en afk
    usage: /<command>
  hc:
    description: Comando para Admins
    usage: /<command>
  hell:
    description: Comando para desplegar la GUI
    usage: /<command>

